name: http_throttle
version: 1.0.3

description: HTTP client middleware that throttles requests.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/http_throttle

environment:
  sdk: '>=2.0.0-dev.17.0 <3.0.0'

dependencies:
  http: '>=0.9.0 <0.12.0'
  pool: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <2.0.0'
